import puppeteer from 'puppeteer-core';
import { startServer, EDGE } from './serve.mjs';
const { server, port } = await startServer();
const browser = await puppeteer.launch({ executablePath: EDGE, headless: true, args: ['--no-sandbox', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage();
await page.setViewport({ width: 1280, height: 720 });
page.on('pageerror', (e) => console.log('[PAGEERROR]', e.message, '\n', (e.stack || '').split('\n').slice(0, 8).join('\n')));
await page.goto(`http://127.0.0.1:${port}/`, { waitUntil: 'load' });
await page.waitForFunction('window.__CITYLINE__ && window.__CITYLINE__.ready()', { timeout: 60000 });
await page.click('#btn-start');
await page.evaluate(() => window.__CITYLINE__.step(45));
console.log('--- forcing end ---');
await page.evaluate(() => { const w = window.__CITYLINE__.world(); for (const o of w.city.objectives) { o.hp = 0; o.lost = true; } window.__CITYLINE__.step(2); });
await new Promise(r => setTimeout(r, 600));
console.log('--- restart ---');
await page.click('#btn-restart');
await new Promise(r => setTimeout(r, 1200));
console.log('--- running 40s ---');
await page.evaluate(() => window.__CITYLINE__.step(40));
await new Promise(r => setTimeout(r, 800));
console.log('snap', JSON.stringify(await page.evaluate(() => window.__CITYLINE__.snapshot())));
await browser.close(); server.close();
