import puppeteer from 'puppeteer-core';
import path from 'node:path';
import { EDGE } from './serve.mjs';
const browser = await puppeteer.launch({ executablePath: EDGE, headless: true, args: ['--no-sandbox', '--enable-unsafe-swiftshader', '--allow-file-access-from-files'] });
const page = await browser.newPage();
await page.setViewport({ width: 1280, height: 720 });
const errs = [];
page.on('pageerror', (e) => errs.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
const url = 'file://' + path.resolve('standalone.html');
await page.goto(url, { waitUntil: 'load' });
await page.waitForFunction('window.__CITYLINE__ && window.__CITYLINE__.ready()', { timeout: 60000 });
await page.click('#btn-start');
await page.evaluate(() => window.__CITYLINE__.step(30));
await page.evaluate(() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))));
await page.screenshot({ path: 'docs/shots/_standalone.png' });
console.log('snapshot', JSON.stringify(await page.evaluate(() => window.__CITYLINE__.snapshot())));
console.log('errors', JSON.stringify(errs.slice(0, 5)));
await browser.close();
